### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by oleksbard** [oleksbard/brackets-custom-css#2]

**Comment by zoutiyx** [comment]
Followed all the steps outlined in your wiki, unfortunately, it doesn't work on my end.

I created a CSS rule, then tried editing it but it wont even open, nor be deleted when the trash icon is pressed.

![image](https://cloud.githubusercontent.com/assets/8180637/3953013/ccff6b06-26e7-11e4-918a-9122a6d504e5.png)

**Comment by oleksbard** [comment]
- Try to update extension (there was an update several hours ago)
- Try to reload Brackets
- Open develop console (`F12`) and look for errors. Please post them here.

**Comment by zoutiyx** [comment]
I installed the extension roughly 7 minutes before posting, so I believe I have the latest extension, (0.1.4).

I have reloaded it and re-installed the extension, same result.

Here is what was returned in the developers console:

![image](https://cloud.githubusercontent.com/assets/8180637/3953517/b898566e-26ec-11e4-859f-4f3aa2630acf.png)

**Comment by oleksbard** [comment]
I had the issue that looks like this several weeks ago: https://github.com/dnbard/brackets-extension-rating/issues/23 In that case another extension (csslint) corrupted Brackets and made impossible to load modules.

**Comment by zoutiyx** [comment]
I have restarted brackets with the Custom CSS extension enabled only, and there were no errors. I have removed the csslint extension but nothing doesn't happen with the Custom CSS Injection. 

This is what is shown in the developer tools with csslint removed:

![image](https://cloud.githubusercontent.com/assets/8180637/3953954/f3a1a45a-26f0-11e4-8c38-261775189072.png)

Is there a way to remove all traces of the custom CSS injection so I could re-install? 
OS: Ubuntu 14.04

**Comment by oleksbard** [comment]
Those errors aren't from CSS Injector.

**Comment by zoutiyx** [comment]
I know. However, when I remove and reinstall CSS Injector via the extension panel,  It still shows all the  CSS rules I created prior, as can seen in my first comment. So like I asked, Is there a way to remove all traces of the custom CSS injection so I could re-install?

**Comment by oleksbard** [comment]
Find and remove `dnbard.custom-css` directory, then restart Brackets. It is somewhere in Brackets Extensions directory. Don't know where it might be on Ubuntu. At Windows it's in `C:\Users\dnbard\AppData\Roaming\Brackets\extensions\user`.

**Comment by zoutiyx** [comment]
That's exactly what I've been doing all along. When it is reinstalled, everything comes back as normal.

**Comment by brunnopleffken** [comment]
![screen shot 2014-08-19 at 10 16 23](https://cloud.githubusercontent.com/assets/3427344/3966435/1a33d34c-27a3-11e4-98eb-6ced5dc6f42f.png)
I'm getting this error on OSX Mavericks (10.9.4)... Seems like the custom CSS file is missing, because I click on "Edit" button and it doesn't work at all...

EDIT: by the way, excellent idea for an extension! I'm tired of editing the main LESS file and reload Brackets... ;)

**Comment by oleksbard** [comment]
@brunnopleffken Do you use latest version of this extension? I've fixed some issues with absolute paths on OS X in #1 issue.

**Comment by brunnopleffken** [comment]
@dnbard I'm using v0.1.4, installed from Brackets' extension manager...

**Comment by brunnopleffken** [comment]
![screen shot 2014-08-19 at 14 13 03](https://cloud.githubusercontent.com/assets/3427344/3969792/25d9eef4-27c4-11e4-9ef5-201aaf231df2.png)
Well, seems like the "cache" folder doesn't exists... I created the folder manually, and it works!!! :)

You can check if the folder exists before creating the CSS file... If it does, OK, otherwise the JS must create the folder manually...

**Comment by oleksbard** [comment]
Yeah. For some strange reasons this folder is missing in extension package in Brackets registry. Good work on this research! Thanks!

**Comment by zoutiyx** [comment]
@dnbard I got it to work. The problem is that CSS Injector's extension is conflicting with one of my other extensions.

###### What I did to get it to work.

deleted the ubuntu equivalent of \AppData\Roaming\Brackets which is /home/user/.config/Brackets

 I'm now trying to find out which one is causing this harm.
